export const POST_CONTACTMESSAGE_REQUEST = 'POST_CONTACTMESSAGE_REQUEST'
export const POST_CONTACTMESSAGE_SUCCESS = 'POST_CONTACTMESSAGE_SUCCESS'
export const POST_CONTACTMESSAGE_FAIL = 'POST_CONTACTMESSAGE_FAIL'
export const POST_CONTACTMESSAGE_RESET = 'POST_CONTACTMESSAGE_RESET'

export const FETCH_CONTACTMESSAGE_REQUEST = 'FETCH_CONTACTMESSAGE_REQUEST'
export const FETCH_CONTACTMESSAGE_SUCCESS = 'FETCH_CONTACTMESSAGE_SUCCESS'
export const FETCH_CONTACTMESSAGE_FAIL = 'FETCH_CONTACTMESSAGE_FAIL'