export const POST_QUANTITATIVESPS_REQUEST = 'POST_QUANTITATIVESPS_REQUEST'
export const POST_QUANTITATIVESPS_SUCCESS = 'POST_QUANTITATIVESPS_SUCCESS'
export const POST_QUANTITATIVESPS_FAIL = 'POST_QUANTITATIVESPS_FAIL'
export const POST_QUANTITATIVESPS_RESET = 'POST_QUANTITATIVESPS_RESET'

export const FETCH_QUANTITATIVESPS_REQUEST = 'FETCH_QUANTITATIVESPS_REQUEST'
export const FETCH_QUANTITATIVESPS_SUCCESS = 'FETCH_QUANTITATIVESPS_SUCCESS'
export const FETCH_QUANTITATIVESPS_FAIL = 'FETCH_QUANTITATIVESPS_FAIL'