export const POST_RESULT_REQUEST = 'POST_RESULT_REQUEST'
export const POST_RESULT_SUCCESS = 'POST_RESULT_SUCCESS'
export const POST_RESULT_FAIL = 'POST_RESULT_FAIL'
export const POST_RESULT_RESET = 'POST_RESULT_RESET'

export const FETCH_RESULT_REQUEST = 'FETCH_RESULT_REQUEST'
export const FETCH_RESULT_SUCCESS = 'FETCH_RESULT_SUCCESS'
export const FETCH_RESULT_FAIL = 'FETCH_RESULT_FAIL'