export const POST_VERBALSPS_REQUEST = 'POST_VERBALSPS_REQUEST'
export const POST_VERBALSPS_SUCCESS = 'POST_VERBALSPS_SUCCESS'
export const POST_VERBALSPS_FAIL = 'POST_VERBALSPS_FAIL'
export const POST_VERBALSPS_RESET = 'POST_VERBALSPS_RESET'

export const FETCH_VERBALSPS_REQUEST = 'FETCH_VERBALSPS_REQUEST'
export const FETCH_VERBALSPS_SUCCESS = 'FETCH_VERBALSPS_SUCCESS'
export const FETCH_VERBALSPS_FAIL = 'FETCH_VERBALSPS_FAIL'