# Generated by Django 4.0.4 on 2022-05-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentalGameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('score', models.IntegerField()),
                ('questions', models.IntegerField()),
                ('speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
