# Generated by Django 4.0.4 on 2022-08-07 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mental', '0002_alter_mentalgameresult_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentalgameresult',
            name='name',
        ),
        migrations.AddField(
            model_name='mentalgameresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
