# Generated by Django 4.0.4 on 2022-08-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental', '0004_quantitativespsec'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantitativespsec',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
